test: Fix urllib.request import (#263)
This is meant to fix:

`AttributeError: module 'urllib' has no attribute 'request'`

Which is showing up in CI now.